import type { ReactNode } from 'react'
import {
  Award,
  BadgeCheck,
  BookOpen,
  Briefcase,
  FileText,
  FlaskConical,
  FolderOpen,
  GraduationCap,
  Heart,
  HeartHandshake,
  IdCard,
  Info,
  Languages,
  Lightbulb,
  Mic,
  Newspaper,
  PenLine,
  Presentation,
  UserCheck,
  Users,
  Wrench,
} from 'lucide-react'
import type { SectionKind } from '@/resume/types'

/** نشانه‌ی هر بخش در رابط؛ هم در ویرایشگر و هم در صفحه‌ی نخست استفاده می‌شود. */
export const sectionIcons: Record<SectionKind, ReactNode> = {
  summary: <FileText />,
  experience: <Briefcase />,
  education: <GraduationCap />,
  skills: <Wrench />,
  softSkills: <Users />,
  languages: <Languages />,
  projects: <FolderOpen />,
  certifications: <BadgeCheck />,
  courses: <BookOpen />,
  awards: <Award />,
  publications: <Newspaper />,
  research: <FlaskConical />,
  teaching: <Presentation />,
  volunteer: <HeartHandshake />,
  memberships: <IdCard />,
  talks: <Mic />,
  patents: <Lightbulb />,
  interests: <Heart />,
  references: <UserCheck />,
  extra: <Info />,
  custom: <PenLine />,
}
